include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    type_annotate_public_apis: true
    avoid_catches_without_on_clauses: true
    evitar_empty_else: true
    avoid_returning_null_for_future: true
    avoid_types_as_parameter_names: true
    control_flow_in_finally: true
    empty_statements: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
    throw_in_finally: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    always_require_non_null_named_parameters: true
    Avoid_catches_without_on_clauses: true
    Avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    prefer_expression_function_bodies: true
    prefer_typing_uninitialized_variables: true
    use_function_type_syntax_for_parameters: true
    always_specify_types: false
    avoid_print: false
    public_member_api_docs: false
    one_member_abstracts: false
