name: pedroermarinho
description: Portfolio

publish_to: "none"

version: 3.0.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  asuka: 2.2.1
  equatable: 2.0.7
  font_awesome_flutter: 10.8.0
  url_launcher: 6.3.1
  shared_preferences: 2.3.3
  dio: 5.7.0
  logger: 2.5.0
  flutter_markdown: 0.7.4+3
  flutter_dotenv: 5.2.1
  get_it: 8.0.3
  result_dart: 2.0.0
  result_command: 1.1.2
  package_info_plus: ^8.1.2
  pdf: ^3.11.1

dev_dependencies:
  effective_dart: 1.3.2
  flutter_launcher_icons: 0.14.2
  mockito: 5.4.4
  build_web_compilers: 4.1.0
  test: 1.25.8
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/octocat.png"

flutter:
  uses-material-design: true
  assets:
    - assets/env
    - assets/octocat.png
    - assets/inspectocat.png
    - assets/settings.json
    - assets/md/about.md
    - assets/md/photo_gimp.md
