name: pedroermarinho
description: Portfolio

publish_to: "none"

version: 2.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dartz: 0.10.1
  asuka: 2.2.1
  equatable: ^2.0.5
  font_awesome_flutter: 10.7.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  flutter_modular: ^5.0.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  logger: ^2.3.0

dev_dependencies:
  effective_dart: ^1.3.2
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.11
  build_web_compilers: ^4.0.10
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/octocat.png"

flutter:
  uses-material-design: true
  assets:
    - assets/octocat.png
    - assets/settings.json
