name: pedroermarinho
description: Portfolio

publish_to: "none"

version: 2.0.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  dartz: 0.10.1
  asuka: 2.2.1
  equatable: 2.0.7
  font_awesome_flutter: 10.8.0
  url_launcher: 6.3.1
  shared_preferences: 2.3.3
  dio: 5.7.0
  flutter_modular: 5.0.3
  logger: 2.5.0
  flutter_markdown: 0.7.4+3
  flutter_dotenv: 5.2.1

dev_dependencies:
  effective_dart: 1.3.2
  flutter_launcher_icons: 0.14.2
  mockito: 5.4.4
  build_runner: 2.4.13
  build_web_compilers: 4.0.11
  test: 1.25.7
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/octocat.png"

flutter:
  uses-material-design: true
  assets:
    - assets/env
    - assets/octocat.png
    - assets/settings.json
