name: pedroermarinho
description: Portfolio

publish_to: "none"

version: 2.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  asuka: ^2.0.1+3
  equatable: ^2.0.5
  font_awesome_flutter: ^10.3.0
  url_launcher: ^6.1.7
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3
  flutter_modular: ^5.0.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  logger: ^1.1.0

dev_dependencies:
  effective_dart: ^1.3.2
  flutter_launcher_icons: ^0.11.0
  mockito: ^5.3.2
  mobx_codegen: ^2.0.7+3
  build_runner: ^2.3.2
  build_web_compilers: ^3.2.7
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/octocat.png"

flutter:
  uses-material-design: true
  assets:
    - assets/octocat.png
    - assets/settings.json
